name: Auto Comment
on: [ issues, pull_request_target ]
jobs:
  auto-comment:
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
          pullRequestOpenedReactions: 'hooray, +1'
          pullRequestOpened: |
            👋 @{{ author }}
            Thanks for opening this pull request! A maintainer will review this soon.
